server:
  port: 9000
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/expensetrackerdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

